{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backup-helper.fullname" . }}
  labels:
    {{- include "restic-backup-helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  restic-password: {{ required "credentials.resticPassword is required when credentials.create is true and credentials.existingSecret is empty" .Values.credentials.resticPassword | quote }}
  {{- if .Values.credentials.msmtprc }}
  msmtprc: |
    {{- .Values.credentials.msmtprc | nindent 4 }}
  {{- end }}
{{- end }}
